"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../../lib/supabase";
const labels:Record<string,string>={submitted:"Pedido recebido",awaiting_payment:"A aguardar pagamento",paid:"Pagamento confirmado",in_progress:"Em execução",review:"Em revisão",awaiting_client:"A aguardar a sua resposta",completed:"Concluído",cancelled:"Cancelado"};
type Order={id:string;status:string;total_amount:number|null;currency:string;created_at:string;notes:string|null;due_at:string|null;services?:{name:string;sla_hours:number|null;expected_deliverable:string|null}|null};
type History={id:string;status:string;note:string|null;created_at:string}; type Message={id:string;message:string;created_at:string;sender_id:string};
export default function OrderRoom(){const[o,setO]=useState<Order|null>(null);const[h,setH]=useState<History[]>([]);const[m,setM]=useState<Message[]>([]);const[newMsg,setNewMsg]=useState("");const[loading,setLoading]=useState(true);
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return}const id=location.pathname.split("/").pop();if(!id)return;const a=await supabase.from("service_orders").select("id,status,total_amount,currency,created_at,notes,due_at,services(name,sla_hours,expected_deliverable)").eq("id",id).eq("customer_id",user.id).single();if(a.error||!a.data){setLoading(false);return}setO(a.data as any);const[b,c]=await Promise.all([supabase.from("order_status_history").select("id,status,note,created_at").eq("order_id",id).order("created_at",{ascending:true}),supabase.from("order_messages").select("id,message,created_at,sender_id").eq("order_id",id).eq("internal",false).order("created_at",{ascending:true})]);setH(b.data||[]);setM(c.data||[]);setLoading(false)}useEffect(()=>{load()},[]);
async function send(){if(!newMsg.trim()||!o)return;const{data:{user}}=await supabase.auth.getUser();if(!user)return;const r=await supabase.from("order_messages").insert({order_id:o.id,sender_id:user.id,message:newMsg.trim(),internal:false});if(!r.error){setNewMsg("");await load()}}
if(loading)return <main style={{padding:50}}>A carregar pedido...</main>;if(!o)return <main style={{padding:50}}>Pedido não encontrado. <a href="/dashboard">Voltar</a></main>;
return <main style={{minHeight:"100vh",background:"#f5f8f5",padding:"35px 6%",color:"#1a261f"}}><div style={{maxWidth:900,margin:"auto"}}><a href="/dashboard">← Área do cliente</a><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",margin:"25px 0"}}><div><p style={{color:"#367052",fontWeight:800,letterSpacing:1}}>SALA DO PEDIDO</p><h1 style={{margin:"5px 0"}}>{o.services?.name||"Serviço"}</h1><p style={{color:"#68756e"}}>Criado em {new Date(o.created_at).toLocaleDateString("pt-MZ")}</p></div><span style={{background:"#eaf4ed",color:"#286042",padding:"9px 13px",borderRadius:20,fontWeight:800}}>{labels[o.status]||o.status}</span></div><div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:18}}><section><div style={{background:"#fff",border:"1px solid #dfe6e1",borderRadius:15,padding:24}}><h2>Progresso</h2>{h.length?h.map(x=><div key={x.id} style={{padding:"14px 0",borderBottom:"1px solid #edf0ed"}}><b>{labels[x.status]||x.status}</b><small style={{display:"block",color:"#78857e"}}>{new Date(x.created_at).toLocaleString("pt-MZ")}</small>{x.note&&<p style={{color:"#68756e"}}>{x.note}</p>}</div>):<p style={{color:"#68756e"}}>O pedido foi recebido e será actualizado à medida que avançar.</p>}</div><div style={{background:"#fff",border:"1px solid #dfe6e1",borderRadius:15,padding:24,marginTop:18}}><h2>Mensagens</h2>{m.map(x=><div key={x.id} style={{background:"#f4f7f4",padding:12,borderRadius:9,margin:"9px 0"}}>{x.message}<small style={{display:"block",color:"#78857e",marginTop:5}}>{new Date(x.created_at).toLocaleString("pt-MZ")}</small></div>)}<textarea value={newMsg} onChange={e=>setNewMsg(e.target.value)} placeholder="Escreva uma mensagem sobre este pedido..." style={{width:"100%",minHeight:90,padding:12,boxSizing:"border-box",border:"1px solid #ccd6cf",borderRadius:8,marginTop:12}}/><button onClick={send} style={{marginTop:10,padding:"11px 16px",background:"#173f2a",color:"#fff",border:0,borderRadius:8,fontWeight:800}}>Enviar mensagem</button></div></section><aside><div style={{background:"#fff",border:"1px solid #dfe6e1",borderRadius:15,padding:22}}><h3>Resumo</h3><p><b>Valor</b><br/>{o.total_amount!=null?o.total_amount.toLocaleString("pt-MZ")+" "+o.currency:"Sob consulta"}</p><p><b>Prazo</b><br/>{o.services?.sla_hours?o.services.sla_hours+" horas após pagamento e documentação completa":"A confirmar"}</p><p><b>Entrega</b><br/>{o.services?.expected_deliverable||"Resultado digital"}</p>{o.due_at&&<p><b>Previsão</b><br/>{new Date(o.due_at).toLocaleString("pt-MZ")}</p>}</div><div style={{background:"#173f2a",color:"#fff",borderRadius:15,padding:22,marginTop:18}}><h3>Próximo passo</h3><p style={{color:"#c8d8ce"}}>{o.status==="submitted"?"Confirme o pagamento para iniciar o prazo de execução.":o.status==="awaiting_client"?"Existe uma informação necessária para continuarmos.":"Acompanhe aqui todas as actualizações do seu pedido."}</p></div></aside></div></div></main>