"use client";
import {useEffect,useState} from "react";
import {ArrowRight,ClipboardList,Clock3,CheckCircle2,AlertCircle} from "lucide-react";
import {supabase} from "../../lib/supabase";

type Order={id:string;status:string;total_amount:number|null;currency:string;created_at:string;due_at:string|null;customer_id:string;services?:{name:string}|null};
const labels:Record<string,string>={submitted:"Recebido",awaiting_payment:"A aguardar pagamento",paid:"Pago",in_progress:"Em execução",review:"Em revisão",awaiting_client:"A aguardar cliente",completed:"Concluído",cancelled:"Cancelado",draft:"Rascunho"};

export default function Operations(){
 const[user,setUser]=useState<any>(null); const[orders,setOrders]=useState<Order[]>([]); const[filter,setFilter]=useState("all"); const[loading,setLoading]=useState(true); const[error,setError]=useState("");
 useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login";return}const p=await supabase.from("profiles").select("full_name,role").eq("id",user.id).single();if(p.data?.role==="customer"){location.href="/dashboard";return}if(p.error){setError("Não foi possível validar o perfil operacional.");setLoading(false);return}setUser({...user,...p.data});const r=await supabase.from("service_orders").select("id,status,total_amount,currency,created_at,due_at,customer_id,services(name)").order("created_at",{ascending:false});if(r.error)setError(r.error.message);else setOrders((r.data as any)||[]);setLoading(false)})()},[]);
 const visible=filter==="all"?orders:orders.filter(o=>o.status===filter);
 const counts={all:orders.length,payment:orders.filter(o=>o.status==="awaiting_payment").length,done:orders.filter(o=>o.status==="completed").length};
 if(loading)return <main className="dashboardShell"><div className="dashboardMain"><p>A carregar operações...</p></div></main>;
 return <main className="dashboardShell"><header className="siteHeader"><a href="/" className="brand"><span className="mark">C</span><span>Conta<span>Express</span></span></a><nav><a href="/operacoes">Operações</a><a href="/servicos">Catálogo</a></nav><div className="login">{user?.full_name||user?.email||"Operador"}</div></header><section className="dashboardMain"><div className="dashboardTop"><div><div className="eyebrow">CENTRO DE OPERAÇÕES</div><h1>Fila de trabalho.</h1><p>Pedidos, SLA, execução e entrega num único espaço operacional.</p></div></div>{error&&<div className="error">{error}</div>}<div className="summaryGrid"><button className="summaryCard" onClick={()=>setFilter("all")}><small>Todos os pedidos</small><strong>{counts.all}</strong></button><button className="summaryCard" onClick={()=>setFilter("in_progress")}><small>Em execução</small><strong>{orders.filter(o=>o.status==="in_progress").length}</strong></button><button className="summaryCard" onClick={()=>setFilter("awaiting_payment")}><small>A aguardar pagamento</small><strong>{counts.payment}</strong></button><button className="summaryCard" onClick={()=>setFilter("completed")}><small>Concluídos</small><strong>{counts.done}</strong></button></div><div className="operationFilters"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Todos</button><button className={filter==="submitted"?"active":""} onClick={()=>setFilter("submitted")}>Novos</button><button className={filter==="paid"?"active":""} onClick={()=>setFilter("paid")}>Pagos</button><button className={filter==="in_progress"?"active":""} onClick={()=>setFilter("in_progress")}>Execução</button><button className={filter==="review"?"active":""} onClick={()=>setFilter("review")}>Revisão</button><button className={filter==="awaiting_client"?"active":""} onClick={()=>setFilter("awaiting_client")}>Cliente</button></div><div className="operationList">{visible.length?visible.map(o=><article className="operationCard" key={o.id}><div className="operationIcon">{o.status==="completed"?<CheckCircle2 size={20}/>:o.status==="awaiting_client"?<AlertCircle size={20}/>:<ClipboardList size={20}/>}</div><div className="operationMain"><div className="operationTitle"><b>{o.services?.name||"Serviço"}</b><span>{labels[o.status]||o.status}</span></div><p>{new Date(o.created_at).toLocaleDateString("pt-MZ")} · Pedido {o.id.slice(0,8).toUpperCase()}</p><small><Clock3 size={14}/> {o.due_at?"Prazo "+new Date(o.due_at).toLocaleString("pt-MZ"):"SLA ainda não iniciado"}</small></div><div className="operationRight"><strong>{o.total_amount!=null?o.total_amount.toLocaleString("pt-MZ")+" "+o.currency:"Sob consulta"}</strong><a href={"/operacoes/"+o.id}>Abrir <ArrowRight size={15}/></a></div></article>):<div className="emptyState"><ClipboardList size={28}/><h3>Não há pedidos nesta fila</h3><p>Quando houver trabalho correspondente ao filtro, aparecerá aqui.</p></div>}</div></section></main>
}